{{/*
Create the name of the service account to use
*/}}
{{- define "serviceAccountName" -}}
{{- if .Values.serviceAccount.create }}
{{- default (include "library-chart.fullname" .) .Values.serviceAccount.name }}
{{- else }}
{{- default "default" .Values.serviceAccount.name }}
{{- end }}
{{- end }}

{{/* Template to generate a ServiceAccount */}}
{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "serviceAccountName" . }}
  labels:
    {{- include "library-chart.labels" . | nindent 4 }}
  {{- if or (.Values.serviceAccount.annotations) (.Values.bucket.enabled) }}
  annotations:
  {{- if .Values.bucket.enabled }}
    iam.gke.io/gcp-service-account: {{ .Values.bucket.serviceAccount }}
  {{- end }}
  {{- with .Values.serviceAccount.annotations }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- end }}
{{- end }}
