apiVersion: v2
name: mlflow
description: MLflow is an open source platform to manage the ML lifecycle, including experimentation, reproducibility, deployment, and a central model registry.
icon: https://minio.lab.sspcloud.fr/projet-onyxia/assets/servicesImg/mlflow.png
keywords:
  - ML
home: https://mlflow.org
sources:
  - https://github.com/statisticsnorway/dapla-lab-helm-charts-experimental

type: application

version: 0.0.1

dependencies:
  - name: postgresql
    version: 12.6.6
    repository: https://charts.bitnami.com/bitnami
  - name: library-chart
    version: 1.0.1
    repository: https://statisticsnorway.github.io/dapla-lab-helm-charts-services
