# Default values for jdemetra.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: trygu/nbdemetra
  tag: "0.7"

discoverable:
  allow: true

liveness:
  enabled: "true"

security:
  networkPolicy:
    enabled: false
    from:
      - ipBlock:
          cidr: 10.233.103.0/32
      - ipBlock:
          cidr: 10.233.111.0/32
  allowlist:
    enabled: true
    ip: "0.0.0.0/0"
  serviceEntry:
    enabled: true
    hosts:
      - "storage.googleapis.com"
  oauth2:
    enabled: false

resources_init:
  limits:
    cpu: "100m"
    memory: "128Mi"

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
