apiVersion: v2
name: doom
description: Face the inferno of data with the same gusto as you would the legions of Hell in Doom. Debug your day with some demon-slaying, and let the only "crunch" be the sound of your victories, not your number-crunching. Perfect for those moments when you need to take a "p-value" break from your statistical analyses and enjoy some p(ain)-value against the forces of darkness. Equip yourself with the BFG (Big Friendly Graph) of classic gaming right here!
type: application

# Version of the chart
version: 0.0.4

# Version of the application
appVersion: "1.0.0"

# Keywords to tag the chart
keywords:
  - Doom
  - ID software

# Home URL for the project
home: https://github.com/CallumHoughton18/Doom-In-Docker

# Sources - where to find the source code and related information
sources:
  - https://github.com/CallumHoughton18/Doom-In-Docker

# Maintainers list
maintainers:
  - name: Trygve Falch
    email: trygve.falch@gmail.com
    url: https://github.com/trygu/

# A list of URLs to images to be used as icons
icon: https://www.giantbomb.com/a/uploads/scale_small/1/16944/2976271-flat%2C800x800%2C075%2Cf.jpg

dependencies:
  - name: library-chart
    version: 3.1.1
    repository: https://statisticsnorway.github.io/dapla-lab-helm-charts-services
