apiVersion: v2
name: doom
description: Swap algorithms for ammo and scatter plots for shotguns in the ultimate data scientist's break. Defrag your brain with Doom's demon hordes – it's the perfect 'escape' key!
type: application

# Version of the chart
version: 0.3.2

# Version of the application
appVersion: "1.0.0"

# Keywords to tag the chart
keywords:
  - Doom
  - ID software

# Home URL for the project
home: https://github.com/CallumHoughton18/Doom-In-Docker

# Sources - where to find the source code and related information
sources:
  - https://github.com/CallumHoughton18/Doom-In-Docker

# Maintainers list
maintainers:
  - name: Trygve Falch
    email: trygve.falch@gmail.com
    url: https://github.com/trygu/

# A list of URLs to images to be used as icons
icon: https://www.giantbomb.com/a/uploads/scale_small/1/16944/2976271-flat%2C800x800%2C075%2Cf.jpg

dependencies:
  - name: library-chart
    version: 3.2.4
    repository: https://statisticsnorway.github.io/dapla-lab-helm-charts-services
