{{- if .Values.buckets.enabled }}
apiVersion: dapla.ssb.no/v1alpha1
kind: WorkloadIdentityAccess
metadata:
  name: {{ include "library-chart.fullname" . }}
spec:
  serviceAccount: {{ include "serviceAccountName" . }}
  groupName: {{ .Values.buckets.group }}
{{- end }}
