# Default values.
global:
  suspend: false

tjeneste:
  image:
    version: "v0"
    pullPolicy: Always

security:
  password: "changeme"
  networkPolicy:
    enabled: false
    from: []
  allowlist:
    enabled: false
    ip: "0.0.0.0/0"
  serviceEntry:
    enabled: true
    hosts:
      - "storage.googleapis.com"
  oauth2:
    provider: keycloak-oidc
    oidcIssuerUrl: "overwritten-by-onyxia"
    clientId: "my-client"
    authenticatedEmails: ""

environment:
  user: onyxia
  group: users
  DATADOC_STATISTICAL_SUBJECT_SOURCE_URL: "https://www.ssb.no/xp/_/service/mimir/subjectStructurStatistics"
  DAPLA_MANUAL_NAMING_STANDARD_URL: "https://probable-waddle-o4w1og1.pages.github.io/statistikkere/navnestandard-datalagring.html"


features:
  toggle_new_variables_workspace: false

userAttributes:
  environmentVariableName: OIDC_TOKEN
  userAttribute: "access_token"
  value: ""

dapla:
  buckets:
    enabled: true
    mountStandard: false
  group: "dapla-felles-developers"

oidc:
  # Specifies whether a config map should be created
  enabled: true
  tokenExchangeUrl: ""
  # The name of the configmap to use.
  # If not set and create is true, a name is generated using the fullname template
  configMapName: ""

replicaCount: 1

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

kubernetes:
  enabled: false
  role: "view"

podAnnotations: {}

podLabels:
  onyxia.app: "datadoc"
  maintained-by-team: "dapla-metadata"

podSecurityContext:
  fsGroup: 100

securityContext:
  {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

networking:
  type: ClusterIP
  clusterIP: None
  service:
    port: 8050
  user:
    enabled: false

istio:
  enabled: false
  gateways:
    - istio-namespace/example-gateway
  hostname: chart-example.local
  userHostname: chart-example-user.local

ressurser:
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube.
  requests:
    cpu: ""
    memory: ""

diskplass:
  enabled: false
  accessMode: ReadWriteOnce
  size: 10Gi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}

startupProbe:
  failureThreshold: 60
  initialDelaySeconds: 10
  periodSeconds: 10
  successThreshold: 1
  timeoutSeconds: 30

deleteJob:
  enabled: true
  cronMinuteAtDay: "0"
  cronHourAtDay: "20"
  imageVersion: "v1.1.0"
  clusterRoleName: onyxia-delete-job
  serviceAccount:
    annotations: {}
