{{ include "library-chart.serviceentry" . }}
---
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: {{ include "library-chart.fullname" . }}-db-serviceentry
spec:
  hosts:
    - "dummy-10.100.0.0.ssb"
  addresses:
    - 10.100.0.0/22
  exportTo:
    - "."
  ports:
    - name: tcp
      number: 3307
      protocol: tcp
  location: MESH_EXTERNAL
